/**
 * @file    main.c
 * @brief   Main program body - application entry point
 * @note    Generated by STM32CubeMX, customized for VectorFOC
 * Copyright (c) 2024 STMicroelectronics. All rights reserved.
 */

#include "main.h"
#include "cmsis_os.h"
#include "application.h"

#include "adc.h"
#include "dma.h"
#include "fdcan.h"
#include "gpio.h"
#include "spi.h"
#include "tim.h"
#include "usart.h"
#include "usb_device.h"
/* Forward declaration for the CubeMX clock setup. */
void SystemClock_Config(void);

void MX_FREERTOS_Init(void);
void MX_IWDG_Init(void);

/**
 * @brief  Application entry point.
 * @retval int (never returns - RTOS takes over)
 */
int main(void) {
  HAL_Init();

  /* CubeMX-generated peripheral initialization sequence. */
  SystemClock_Config();
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_ADC1_Init();
  MX_FDCAN1_Init();
  MX_SPI1_Init();
  MX_TIM3_Init();
  MX_TIM1_Init();
  MX_ADC2_Init();
  MX_USART1_UART_Init();
  MX_IWDG_Init();

  /* Application-level initialization (motor_runtime, comm, safety, etc.) */
  App_Init();

  /* Create FreeRTOS threads and start scheduler */
  MX_FREERTOS_Init();
  osKernelStart();

  /* Should never reach here */
  while (1) {
  }
}

/**
 * @brief  IWDG initialization (register-based, no HAL).
 *         Prescaler=32, Reload=100 => ~100ms timeout at 32kHz LSI.
 */
void MX_IWDG_Init(void) {
  IWDG->KR = 0xCCCC;  /* Enable IWDG */
  IWDG->KR = 0x5555;  /* Enable write access */
  IWDG->PR = 0x03;    /* Prescaler /32 */
  IWDG->RLR = 100;    /* Reload value for ~100ms */
  while (IWDG->SR != 0)
    ;                  /* Wait for register update */
  IWDG->KR = 0xAAAA;  /* Reload counter */
}

/**
 * @brief  System clock configuration.
 *         HSE 8MHz -> PLL -> 168MHz SYSCLK
 */
void SystemClock_Config(void) {
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1_BOOST);

  /* Configure HSE + HSI48 + PLL */
  RCC_OscInitStruct.OscillatorType =
      RCC_OSCILLATORTYPE_HSI48 | RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSI48State = RCC_HSI48_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV1;
  RCC_OscInitStruct.PLL.PLLN = 42;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
    Error_Handler();
  }

  /* Configure HCLK, SYSCLK, PCLK1, PCLK2 */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                                RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK) {
    Error_Handler();
  }
}

/**
 * @brief  TIM17 period elapsed callback - HAL tick increment.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
  if (htim->Instance == TIM17) {
    HAL_IncTick();
  }
}

/**
 * @brief  Global error handler. Disables IRQ and waits for watchdog reset.
 */
void Emergency_DisableBridgeOutputs(void) {
  TIM1->BDTR &= ~TIM_BDTR_MOE;
  TIM1->CCER &= ~(TIM_CCER_CC1E | TIM_CCER_CC1NE |
                  TIM_CCER_CC2E | TIM_CCER_CC2NE |
                  TIM_CCER_CC3E | TIM_CCER_CC3NE);
  __DSB();
  __ISB();
}
void Emergency_Shutdown(void) {
  __disable_irq();
  Emergency_DisableBridgeOutputs();
}
void Error_Handler(void) {
  Emergency_Shutdown();
  #include "error_configuration.h"
  #ifdef USE_ERROR_MANAGER
    #include "error_manager.h"
    #include "error_types.h"
    ERROR_REPORT(ERROR_SYSTEM_FATAL, "Error_Handler called");
  #endif

  __disable_irq();
  while (1) {
    /* Wait for watchdog reset */
  }
}

#ifdef USE_FULL_ASSERT
void assert_fail(uint8_t *file, uint32_t line) {
  /* Override to add custom assert reporting */
}
#endif
