#ifndef TEST_APP_INIT_BINDING_MOCKS_PARAM_TABLE_H
#define TEST_APP_INIT_BINDING_MOCKS_PARAM_TABLE_H
typedef enum { PARAM_OK = 0, PARAM_ERR_INVALID_INDEX, PARAM_ERR_INVALID_TYPE, PARAM_ERR_READONLY, PARAM_ERR_OUT_OF_RANGE, PARAM_ERR_NULL_PTR, PARAM_ERR_STORAGE } ParamResult;
#endif