/**
 * @file    app_freertos.c
 * @brief   FreeRTOS task creation and OS hooks
 * @note    Generated by STM32CubeMX, customized for VectorFOC
 * Copyright (c) 2024 STMicroelectronics. All rights reserved.
 */

#include "FreeRTOS.h"
#include "cmsis_os.h"
#include "main.h"
#include "task.h"

#include "rtos/rtos_tasks.h"
#include "usb_device.h"

/* Task handles */
osThreadId defaultTaskHandle;
osThreadId guardtaskHandle;
osThreadId customtaskHandle;

#define DEFAULT_TASK_STACK_DEPTH 256U
#define GUARD_TASK_STACK_DEPTH   256U
#define COMM_TASK_STACK_DEPTH    512U

/*
 * The debug stack is CPU-only and shares CCM with the encoder calibration
 * workspace. Guard/communication stacks remain in regular SRAM to preserve
 * headroom in both physical RAM banks.
 */
static StackType_t xDefaultTaskStack[DEFAULT_TASK_STACK_DEPTH]
    __attribute__((section(".ccm_bss"), aligned(8)));
static StackType_t xGuardTaskStack[GUARD_TASK_STACK_DEPTH];
static StackType_t xCommTaskStack[COMM_TASK_STACK_DEPTH];
static StaticTask_t xDefaultTaskTCB;
static StaticTask_t xGuardTaskTCB;
static StaticTask_t xCommTaskTCB;

/* Task entry point declarations (implemented in Src/APP/rtos/) */
void StartDefaultTask(void const *argument);
void StartGuardTask(void const *argument);
void StartCustomTask(void const *argument);

void MX_FREERTOS_Init(void);

/* Static allocation for idle task */
void vApplicationGetIdleTaskMemory(StaticTask_t **ppxIdleTaskTCBBuffer,
                                   StackType_t **ppxIdleTaskStackBuffer,
                                   uint32_t *pulIdleTaskStackSize);

/* OS hook prototypes */
void vApplicationIdleHook(void);
void vApplicationStackOverflowHook(xTaskHandle xTask, signed char *pcTaskName);
void vApplicationMallocFailedHook(void);

__weak void vApplicationIdleHook(void) {
  /* Called on each idle task iteration. Must never block. */
}

__weak void vApplicationStackOverflowHook(xTaskHandle xTask,
                                          signed char *pcTaskName) {
  (void)xTask;
  (void)pcTaskName;
  Error_Handler();
}

__weak void vApplicationMallocFailedHook(void) {
  Error_Handler();
}

static StaticTask_t xIdleTaskTCBBuffer;
static StackType_t xIdleStack[configMINIMAL_STACK_SIZE];

void vApplicationGetIdleTaskMemory(StaticTask_t **ppxIdleTaskTCBBuffer,
                                   StackType_t **ppxIdleTaskStackBuffer,
                                   uint32_t *pulIdleTaskStackSize) {
  *ppxIdleTaskTCBBuffer = &xIdleTaskTCBBuffer;
  *ppxIdleTaskStackBuffer = &xIdleStack[0];
  *pulIdleTaskStackSize = configMINIMAL_STACK_SIZE;
}

/**
 * @brief  FreeRTOS initialization - create all application tasks.
 */
void MX_FREERTOS_Init(void) {
  /* Debug task: USB/VOFA data output (1kHz) */
  osThreadStaticDef(defaultTask, StartDefaultTask, osPriorityNormal, 0,
                    DEFAULT_TASK_STACK_DEPTH, xDefaultTaskStack,
                    &xDefaultTaskTCB);
  defaultTaskHandle = osThreadCreate(osThread(defaultTask), NULL);

  /* Guard task: motor safety monitoring + LED (200Hz) */
  osThreadStaticDef(guardtask, StartGuardTask, osPriorityNormal, 0,
                    GUARD_TASK_STACK_DEPTH, xGuardTaskStack, &xGuardTaskTCB);
  guardtaskHandle = osThreadCreate(osThread(guardtask), NULL);

  /* Communication task: CAN command processing (500Hz) */
  osThreadStaticDef(customtask, StartCustomTask, osPriorityAboveNormal, 0,
                    COMM_TASK_STACK_DEPTH, xCommTaskStack, &xCommTaskTCB);
  customtaskHandle = osThreadCreate(osThread(customtask), NULL);

  if (defaultTaskHandle == NULL || guardtaskHandle == NULL ||
      customtaskHandle == NULL) {
    Error_Handler();
  }
}
