/**
 * @file error_types.h
 * @brief 统一错误类型定义 - 全系统错误码体系
 * @version 3.0
 * @date 2026-01-28
 * 
 * @details 错误码结构 (32-bit):
 * - [31:28] 严重级别 (0-15)
 * - [27:24] 错误域 (0-15)
 * - [23:16] 子系统 (0-255)
 * - [15:0]  具体错误 (0-65535)
 */

#ifndef ERROR_TYPES_H
#define ERROR_TYPES_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ========== 错误级别定义 ========== */
typedef enum {
    ERROR_SEVERITY_INFO     = 0,  /**< 信息 - 仅记录 */
    ERROR_SEVERITY_WARNING  = 1,  /**< 警告 - 需要注意但不停机 */
    ERROR_SEVERITY_MINOR    = 2,  /**< 轻微故障 - 降额运行 */
    ERROR_SEVERITY_MAJOR    = 3,  /**< 严重故障 - 立即停机 */
    ERROR_SEVERITY_CRITICAL = 4,  /**< 致命故障 - 系统复位 */
} ErrorSeverity;

/* ========== 错误域定义 ========== */
typedef enum {
    ERROR_DOMAIN_SYSTEM       = 0,  /**< 系统层 (HAL/BSP) */
    ERROR_DOMAIN_HARDWARE     = 1,  /**< 硬件层 (外设/驱动) */
    ERROR_DOMAIN_MOTOR        = 2,  /**< 电机层 (FOC/控制) */
    ERROR_DOMAIN_SAFETY       = 3,  /**< 安全层 (保护/故障) */
    ERROR_DOMAIN_COMMUNICATION = 4, /**< 通信层 (协议/CAN) */
    ERROR_DOMAIN_CALIBRATION  = 5,  /**< 校准层 */
    ERROR_DOMAIN_PARAMETER    = 6,  /**< 参数层 */
    ERROR_DOMAIN_APPLICATION  = 7,  /**< 应用层 */
} ErrorDomain;

/* ========== 子系统定义 ========== */
/* 系统层子系统 */
#define ERROR_SUBSYS_SYSTEM_INIT    0x00
#define ERROR_SUBSYS_SYSTEM_CLOCK   0x01
#define ERROR_SUBSYS_SYSTEM_MEMORY  0x02

/* 硬件层子系统 */
#define ERROR_SUBSYS_HW_ADC         0x00
#define ERROR_SUBSYS_HW_PWM         0x01
#define ERROR_SUBSYS_HW_CAN         0x02
#define ERROR_SUBSYS_HW_UART        0x03
#define ERROR_SUBSYS_HW_SPI         0x04
#define ERROR_SUBSYS_HW_ENCODER     0x05
#define ERROR_SUBSYS_HW_FLASH       0x06

/* 电机层子系统 */
#define ERROR_SUBSYS_MOTOR_FOC      0x00
#define ERROR_SUBSYS_MOTOR_CONTROL  0x01
#define ERROR_SUBSYS_MOTOR_FSM      0x02

/* 安全层子系统 */
#define ERROR_SUBSYS_SAFETY_VOLTAGE 0x00
#define ERROR_SUBSYS_SAFETY_CURRENT 0x01
#define ERROR_SUBSYS_SAFETY_TEMP    0x02
#define ERROR_SUBSYS_SAFETY_SPEED   0x03
#define ERROR_SUBSYS_SAFETY_STALL   0x04
#define ERROR_SUBSYS_SAFETY_ENCODER 0x05

/* 通信层子系统 */
#define ERROR_SUBSYS_COMM_PARSE     0x00
#define ERROR_SUBSYS_COMM_TIMEOUT   0x01
#define ERROR_SUBSYS_COMM_PROTOCOL  0x02

/* 校准层子系统 */
#define ERROR_SUBSYS_CALIB_CURRENT  0x00
#define ERROR_SUBSYS_CALIB_RESISTANCE 0x01
#define ERROR_SUBSYS_CALIB_INDUCTANCE 0x02
#define ERROR_SUBSYS_CALIB_ENCODER  0x03
#define ERROR_SUBSYS_CALIB_FLUX     0x04

/* 参数层子系统 */
#define ERROR_SUBSYS_PARAM_ACCESS   0x00
#define ERROR_SUBSYS_PARAM_STORAGE  0x01
#define ERROR_SUBSYS_PARAM_VALIDATE 0x02

/* ========== 错误码构造宏 ========== */
#define ERROR_CODE(severity, domain, subsys, code) \
    (((uint32_t)(severity) << 28) | \
     ((uint32_t)(domain) << 24) | \
     ((uint32_t)(subsys) << 16) | \
     ((uint32_t)(code)))

/* ========== 错误码解析宏 ========== */
#define ERROR_GET_SEVERITY(err)  (ErrorSeverity)(((err) >> 28) & 0x0F)
#define ERROR_GET_DOMAIN(err)    (ErrorDomain)(((err) >> 24) & 0x0F)
#define ERROR_GET_SUBSYS(err)    (uint8_t)(((err) >> 16) & 0xFF)
#define ERROR_GET_CODE(err)      (uint16_t)((err) & 0xFFFF)

/* ========== 预定义错误码 ========== */
#define ERROR_NONE  0x00000000

/* 系统错误 */
#define ERROR_SYSTEM_INIT_FAILED     ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_SYSTEM, ERROR_SUBSYS_SYSTEM_INIT, 0x0001)
#define ERROR_SYSTEM_CLOCK_CONFIG    ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_SYSTEM, ERROR_SUBSYS_SYSTEM_CLOCK, 0x0001)
#define ERROR_SYSTEM_TIMEOUT         ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_SYSTEM, ERROR_SUBSYS_SYSTEM_INIT, 0x0002)
#define ERROR_SYSTEM_OUT_OF_MEMORY   ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SYSTEM, ERROR_SUBSYS_SYSTEM_MEMORY, 0x0001)
#define ERROR_SYSTEM_FATAL           ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_SYSTEM, ERROR_SUBSYS_SYSTEM_INIT, 0x00FF)

/* 硬件错误 */
#define ERROR_HW_ADC_INIT            ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_ADC, 0x0001)
#define ERROR_HW_ADC_TIMEOUT         ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_ADC, 0x0002)
#define ERROR_HW_PWM_INIT            ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_PWM, 0x0001)
#define ERROR_HW_PWM_DEADTIME        ERROR_CODE(ERROR_SEVERITY_CRITICAL, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_PWM, 0x0002)
#define ERROR_HW_CAN_INIT            ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_CAN, 0x0001)
#define ERROR_HW_CAN_TX_FULL         ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_CAN, 0x0002)
#define ERROR_HW_ENCODER_SPI         ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_ENCODER, 0x0001)
#define ERROR_HW_ENCODER_LOSS        ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_HARDWARE, ERROR_SUBSYS_HW_ENCODER, 0x0002)

/* 电机错误 */
#define ERROR_MOTOR_STALL            ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_MOTOR, 0, 0x0001)
#define ERROR_MOTOR_ENCODER_LOSS     ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_MOTOR, 0, 0x0002)
#define ERROR_MOTOR_ENCODER_SPI      ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_MOTOR, 0, 0x0003)

/* 安全故障（映射FaultBit） */
#define ERROR_SAFETY_OVERTEMP        ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_TEMP, 0x0001)
#define ERROR_SAFETY_OVERVOLTAGE     ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_VOLTAGE, 0x0001)
#define ERROR_SAFETY_UNDERVOLTAGE    ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_VOLTAGE, 0x0002)
#define ERROR_SAFETY_OVERCURRENT     ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_CURRENT, 0x0001)
#define ERROR_SAFETY_OVER_CURRENT_A  ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_CURRENT, 0x0001)
#define ERROR_SAFETY_OVER_CURRENT_B  ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_CURRENT, 0x0002)
#define ERROR_SAFETY_OVER_CURRENT_C  ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_CURRENT, 0x0003)
#define ERROR_SAFETY_OVER_SPEED      ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_SPEED, 0x0001)
#define ERROR_SAFETY_STALL           ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_STALL, 0x0001)
#define ERROR_SAFETY_ENCODER_UNCALIB ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_SAFETY, ERROR_SUBSYS_SAFETY_ENCODER, 0x0001)

/* 通信错误 */
#define ERROR_COMM_TIMEOUT           ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_COMMUNICATION, ERROR_SUBSYS_COMM_TIMEOUT, 0x0001)
#define ERROR_COMM_PARSE_FAILED      ERROR_CODE(ERROR_SEVERITY_INFO, ERROR_DOMAIN_COMMUNICATION, ERROR_SUBSYS_COMM_PARSE, 0x0001)
#define ERROR_COMM_UNKNOWN_ID        ERROR_CODE(ERROR_SEVERITY_INFO, ERROR_DOMAIN_COMMUNICATION, ERROR_SUBSYS_COMM_PARSE, 0x0002)
#define ERROR_COMM_INVALID_DATA      ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_COMMUNICATION, ERROR_SUBSYS_COMM_PARSE, 0x0003)
#define ERROR_COMM_INVALID_FRAME     ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_COMMUNICATION, ERROR_SUBSYS_COMM_PARSE, 0x0004)

/* 校准错误 */
#define ERROR_CALIB_INVALID_PARAMS   ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_CURRENT, 0x00FF)
#define ERROR_CALIB_CURRENT_FAILED   ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_CURRENT, 0x0001)
#define ERROR_CALIB_RESISTANCE_FAILED ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_RESISTANCE, 0x0001)
#define ERROR_CALIB_INDUCTANCE_FAILED ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_INDUCTANCE, 0x0001)
#define ERROR_CALIB_ENCODER_FAILED   ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_ENCODER, 0x0001)
#define ERROR_CALIB_FLUX_FAILED      ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_CALIBRATION, ERROR_SUBSYS_CALIB_FLUX, 0x0001)

/* 参数错误 */
#define ERROR_PARAM_NULL_PTR         ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x0000)
#define ERROR_PARAM_INVALID_INDEX    ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x0001)
#define ERROR_PARAM_READ_ONLY        ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x0002)
#define ERROR_PARAM_ACCESS_DENIED    ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x0003)
#define ERROR_PARAM_OUT_OF_RANGE     ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_VALIDATE, 0x0001)
#define ERROR_PARAM_INVALID_VALUE    ERROR_CODE(ERROR_SEVERITY_WARNING, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_VALIDATE, 0x0002)
#define ERROR_PARAM_WRITE_FAILED     ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x00FF)
#define ERROR_PARAM_READ_FAILED      ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_ACCESS, 0x00FE)
#define ERROR_PARAM_FLASH_WRITE      ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_STORAGE, 0x0001)
#define ERROR_PARAM_FLASH_READ       ERROR_CODE(ERROR_SEVERITY_MAJOR, ERROR_DOMAIN_PARAMETER, ERROR_SUBSYS_PARAM_STORAGE, 0x0002)

/* ========== 错误记录结构 ========== */
typedef struct {
    uint32_t error_code;       /**< 错误码 */
    uint32_t timestamp;        /**< 时间戳 (ms) */
    const char *message;       /**< 错误消息字符串 */
    const char *file;          /**< 源文件名 */
    uint32_t line;             /**< 源文件行号 */
} ErrorRecord;

/* ========== 错误回调类型 ========== */
typedef void (*ErrorCallback)(const ErrorRecord *record);

#endif /* ERROR_TYPES_H */
