#ifndef POSITION_SENSOR_BUILD_CONFIG_H
#define POSITION_SENSOR_BUILD_CONFIG_H

#include "board_config.h"

/*
 * Build-time storage decisions use generic capabilities. Concrete sensor-mode
 * checks remain confined to this module so ALGO never names a device model.
 */
#if HW_POSITION_SENSOR_MODE == HW_POSITION_SENSOR_MT6816 ||                    \
    HW_POSITION_SENSOR_MODE == HW_POSITION_SENSOR_TMR3109
#define POSITION_SENSOR_BUILD_HAS_PERSISTENT_CALIBRATION 1
#define POSITION_SENSOR_BUILD_HAS_RAW_DIRECTION_POLE 1
#define POSITION_SENSOR_BUILD_HAS_LINEARITY_CALIBRATION 1
#else
#define POSITION_SENSOR_BUILD_HAS_PERSISTENT_CALIBRATION 1
#define POSITION_SENSOR_BUILD_HAS_RAW_DIRECTION_POLE 0
#define POSITION_SENSOR_BUILD_HAS_LINEARITY_CALIBRATION 0
#endif

#endif /* POSITION_SENSOR_BUILD_CONFIG_H */
