#ifndef TEST_APP_COMM_BOOTSTRAP_PROTOCOL_TYPES_H
#define TEST_APP_COMM_BOOTSTRAP_PROTOCOL_TYPES_H

typedef enum {
  PROTOCOL_VECTOR = 0,
  PROTOCOL_CANOPEN = 1,
  PROTOCOL_MIT = 2,
} ProtocolType;

#endif /* TEST_APP_COMM_BOOTSTRAP_PROTOCOL_TYPES_H */
